import { SEO } from "@/app/components/SEO";
import { CtaLink, PageHero, ProductGrid, Section } from "@/app/components/MarketingComponents";
import { createBreadcrumbSchema } from "@/app/lib/structuredData";

const whyNow = ["Operational data volume has outgrown manual correlation.", "Operations span more systems, vendors, and service providers.", "AI requires trustworthy identity, evidence, and time-correct context.", "Closed tickets no longer provide enough proof of operational recovery.", "Industry needs accountable automation, not more disconnected alerts."];
export function AboutPage() {
  const description = "Last Mile was founded to create the vendor-independent operating layer between operational evidence, governed action, and verified physical recovery.";
  return <><SEO title="About Last Mile | Closing the Physical Operations Loop" description={description} canonicalPath="/about" markdownPath="/about.md" jsonLd={createBreadcrumbSchema([{ name: "Home", path: "/" }, { name: "About", path: "/about" }])} />
    <PageHero eyebrow="About Last Mile" title="Built to close the distance between operational systems and physical outcomes." intro="Last Mile was founded on a simple observation: enterprise platforms transformed digital work, but physical operations still lack a vendor-independent layer that connects operational evidence to coordinated action and verified recovery." actions={<CtaLink to="/contact?intent=operation">Discuss Your Operation</CtaLink>} />
    <Section eyebrow="The category insight" title="The last mile in operations is accountability."><div className="lm-copy-stack"><p>Organizations already have strong systems for control, monitoring, telemetry, equipment management, work, enterprise workflow, analytics, and service execution. The unresolved problem is the complete path between those systems.</p><p>That is where identity fragments, context is rebuilt, ownership becomes unclear, action crosses authority boundaries, and a closed ticket is mistaken for physical recovery. Last Mile is building the Physical Operations Platform to make that path accountable.</p></div></Section>
    <Section eyebrow="Founder" title="Experience across enterprise platforms revealed the missing operating layer." tone="wash"><div className="lm-founder"><div><h3>Rodney Runolfson</h3><p>Founder and CEO</p></div><div><p>Rodney brings decades of enterprise-platform strategy and implementation experience, including building and leading a major ServiceNow practice at Deloitte. That work showed how a shared platform could transform digital workflows—and where physical operations remained disconnected across controls, data, work, providers, and evidence.</p><p>That experience is the source of the Last Mile insight, not a continuing dependency. The Last Mile Platform is vendor-independent by design and works above the operational and enterprise systems customers already trust.</p></div></div></Section>
    <Section eyebrow="Why now" title="Physical operations have outgrown disconnected response."><ol className="lm-why-now">{whyNow.map((item, index) => <li key={item}><span>{String(index + 1).padStart(2, "0")}</span><strong>{item}</strong></li>)}</ol></Section>
    <Section eyebrow="One platform" title="Four integrated capabilities, one accountable response." tone="wash"><ProductGrid /></Section>
    <Section eyebrow="Build with operators" title="Prove the loop with real Conditions and measurable outcomes." tone="dark"><div className="lm-copy-stack"><p>Last Mile begins with a consequential operational Condition, the systems and people involved, the authority required to respond, and the live evidence that proves recovery.</p><CtaLink to="/contact?intent=design-partnership">Explore a Design Partnership</CtaLink></div></Section>
  </>;
}
