import { SEO } from "@/app/components/SEO";
import { ProductPageLayout } from "@/app/components/ProductPageLayout";
import { createBreadcrumbSchema, createProductSchema } from "@/app/lib/structuredData";

export function InfinitFlowPage() {
  const description="Infinit-Flow connects a qualified Condition to governed work, approvals, escalation, providers, acknowledgements, and authorized enterprise-system action.";
  return <><SEO title="Infinit-Flow | Coordinate and Act on Operational Conditions" description={description} canonicalPath="/infinit-flow" jsonLd={[createProductSchema("Infinit-Flow","/infinit-flow",description),createBreadcrumbSchema([{name:"Home",path:"/"},{name:"Infinit-Flow",path:"/infinit-flow"}])]} />
  <ProductPageLayout eyebrow="Coordinate + Act" title="Turn a confirmed Condition into governed action across people, platforms, and providers." intro="Infinit-Flow connects the Condition, response plan, assignments, approvals, escalation, enterprise-system actions, provider coordination, and acknowledgements in one accountable execution path." heroNote="Current proof scope: predefined governed workflow for Data Center Cooling" primaryCta={{label:"Discuss Your Response Path",to:"/contact?intent=operation"}} secondaryCta={{label:"Explore Data Center Cooling",to:"/data-center-cooling"}}
    overview={{heading:"Coordinate action without overstepping authority.",copy:["Infinit-Flow preserves the Condition, decisions, ownership, approvals, work, acknowledgements, and outcome evidence as the response crosses organizational and system boundaries."],children:<><div className="lm-proof"><strong>Current proof scope</strong><p>The Data Center Cooling reference implementation uses a predefined governed workflow. Generalized visual authoring and reusable workflow-building capabilities will expand after customer validation.</p></div><div className="lm-mode-grid"><article><strong>ASSIST mode</strong><p>Recommends and prepares actions while a person retains execution authority.</p></article><article><strong>AUTO mode</strong><p>Executes only actions explicitly authorized by policy and system permissions.</p></article><article><strong>Required human approval</strong><p>Stops at defined gates where judgment, risk, or authority requires a person.</p></article><article><strong>Enterprise-system action</strong><p>Creates or updates approved work and workflow records through governed integrations.</p></article><article><strong>Direct equipment control</strong><p>PLC, SCADA, SIS, BMS, and process control remain outside the baseline platform.</p></article></div></>}}
    benefits={[{title:"One accountable execution path"},{title:"Explicit ownership and acknowledgement"},{title:"Policy-bound approvals and escalation"},{title:"Provider and enterprise-system coordination"},{title:"Complete decision and action evidence"},{title:"Visible failure and recovery paths"}]}
    features={[{title:"Condition-triggered response plans"},{title:"Assignments and acknowledgements"},{title:"Approval and authority gates"},{title:"Timers and escalation"},{title:"Authorized enterprise-system actions"},{title:"Outcome and evidence write-back"}]}
    useCases={["Predefined Data Center Cooling response workflow","Facilities and service-provider coordination","Cross-system maintenance response","Quality hold and approval path","Shift escalation and acknowledgement","Authorized CMMS or enterprise workflow updates"]}
    relatedProducts={[{label:"Infinit-Signal",to:"/infinit-signal",copy:"Qualifies the Condition."},{label:"Singularity",to:"/singularity",copy:"Supplies identity, topology, and context."},{label:"Infinit-Control",to:"/infinit-control",copy:"Shows the live response and result."},{label:"Last Mile Platform",to:"/platform"}]}
    faqs={[{question:"Is generalized drag-and-drop authoring complete?",answer:"No. The current commercial proof uses a predefined governed Data Center Cooling workflow. General authoring will expand after customer validation."},{question:"Does Infinit-Flow directly control equipment?",answer:"Not as a baseline capability. Direct PLC, SCADA, SIS, BMS, or process control remains with established control systems and their safety boundaries."},{question:"Can people remain in control?",answer:"Yes. ASSIST mode, explicit approval gates, assignments, acknowledgements, and exceptions keep authority visible."}]}
    resources={[{label:"Data Center Cooling reference use case",to:"/data-center-cooling"},{label:"Platform overview",to:"/platform"},{label:"Signal 2 Action",to:"/signal-to-action"}]} />
  </>;
}
