import { SEO } from "@/app/components/SEO";
import { ProductPageLayout } from "@/app/components/ProductPageLayout";
import { createBreadcrumbSchema, createProductSchema } from "@/app/lib/structuredData";

export function InfinitSignalPage() {
  const description="Infinit-Signal acquires and qualifies operational evidence, preserving quality, timing, source context, lineage, and accountable Conditions for Singularity.";
  return <><SEO title="Infinit-Signal | Observe and Qualify Operational Evidence" description={description} canonicalPath="/infinit-signal" jsonLd={[createProductSchema("Infinit-Signal","/infinit-signal",description),createBreadcrumbSchema([{name:"Home",path:"/"},{name:"Infinit-Signal",path:"/infinit-signal"}])]} />
  <ProductPageLayout eyebrow="Observe + Qualify" title="Turn raw operational signals into one accountable Condition." intro="Infinit-Signal acquires operational evidence from the systems customers already use, validates its quality and timing, resolves source context, and creates trusted SSOM-conformant operational records for Singularity." primaryCta={{label:"Discuss Your Source Environment",to:"/contact?intent=architecture"}} secondaryCta={{label:"Explore Data Center Cooling",to:"/data-center-cooling"}}
    overview={{heading:"Qualify evidence before response begins.",copy:["A signal is not automatically a problem. It may be stale, duplicated, late, replayed, incomplete, expected, or disconnected from the affected asset. Infinit-Signal establishes whether the evidence is trustworthy and whether it represents an accountable operational Condition."],children:<RolePanel rows={[["Receives","Telemetry, events, alarms, equipment state, and source metadata"],["Determines","Quality, freshness, duplicates, late data, replay, affected asset, and operational meaning"],["Produces","Assets, Observations, evidence, lineage, and accountable Conditions"],["Does not replace","MQTT brokers, OPC UA systems, historians, SCADA, MES, or BMS"]]} />}}
    benefits={[{title:"Separate noise from Conditions",copy:"Qualify evidence before work, approvals, or automation begin."},{title:"Preserve source context",copy:"Keep timing, quality, provenance, and lineage connected to the Condition."},{title:"Resolve affected assets",copy:"Connect observations to identity, topology, location, and operational impact."}]}
    features={[{title:"Source profiles and acquisition"},{title:"Quality and freshness evaluation"},{title:"Duplicate, replay, and late-data classification"},{title:"Asset and topology resolution"},{title:"SSOM-conformant Observations"},{title:"Condition evidence and lineage"}]}
    useCases={["Data Center Cooling thermal excursions","Equipment-state and performance degradation","Quality exceptions tied to affected production assets","Energy anomalies requiring accountable investigation","Source-health and evidence-quality failures"]}
    relatedProducts={[{label:"Singularity",to:"/singularity",copy:"Understands and remembers the qualified evidence."},{label:"Infinit-Flow",to:"/infinit-flow",copy:"Coordinates the governed response."},{label:"Infinit-Control",to:"/infinit-control",copy:"Shows the live Condition and outcome."},{label:"Last Mile Platform",to:"/platform"}]}
    faqs={[{question:"Does Infinit-Signal replace a broker or historian?",answer:"No. It acquires evidence from existing source systems and preserves the context needed to qualify and act on that evidence."},{question:"What is a Condition?",answer:"A Condition is a qualified operational issue with identity, affected topology, severity, confidence, evidence, lifecycle, and response context."}]}
    resources={[{label:"Platform overview",to:"/platform"},{label:"Data Center Cooling reference use case",to:"/data-center-cooling"},{label:"Signal 2 Action",to:"/signal-to-action"}]}
    finalCta={{heading:"Bring one consequential Condition into focus.",copy:["Show us the source systems, evidence gaps, and response path your team needs to make accountable."],label:"Discuss Your Source Environment",to:"/contact?intent=architecture"}} />
  </>;
}

function RolePanel({rows}:{rows:string[][]}) { return <dl className="lm-role-panel">{rows.map(([term,detail])=><div key={term}><dt>{term}</dt><dd>{detail}</dd></div>)}</dl>; }
