import { SEO } from "@/app/components/SEO";
import { ProductPageLayout } from "@/app/components/ProductPageLayout";
import { createBreadcrumbSchema, createProductSchema } from "@/app/lib/structuredData";

export function InfinitControlPage() {
  const description="Infinit-Control is the role-based command surface for a live Condition, affected topology, evidence, coordinated work, current telemetry, and verified outcomes.";
  return <><SEO title="Infinit-Control | See and Verify Physical Outcomes" description={description} canonicalPath="/infinit-control" jsonLd={[createProductSchema("Infinit-Control","/infinit-control",description),createBreadcrumbSchema([{name:"Home",path:"/"},{name:"Infinit-Control",path:"/infinit-control"}])]} />
  <ProductPageLayout eyebrow="See + Verify" title="See the live Condition, coordinated work, and verified physical outcome in one command surface." intro="Infinit-Control gives operators and leaders one role-based view of the Condition, affected assets, evidence, active work, decisions, current telemetry, and verified outcome." primaryCta={{label:"Discuss Your Command Surface",to:"/contact?intent=operation"}} secondaryCta={{label:"Explore the Platform",to:"/platform"}}
    overview={{heading:"A command surface, not another generic dashboard.",copy:["Infinit-Control draws from Singularity and the active platform response. It does not create a separate truth store. It gives each role the context needed to understand the Condition, see who owns the response, inspect current evidence, and determine whether the physical operation recovered."],children:<div className="lm-experience-list">{["Live Condition and affected topology","Evidence and confidence","Active response and owner","Workflow state and approvals","Current telemetry and freshness","Verified recovery or recurrence","Cross-site learning and comparison where policy permits"].map((item)=><span key={item}>{item}</span>)}</div>}}
    benefits={[{title:"One view of Condition and response"},{title:"Evidence and confidence in context"},{title:"Live ownership and approval state"},{title:"Return telemetry beside completed work"},{title:"Role-based operational focus"},{title:"Recurrence visible after recovery"}]}
    features={[{title:"Condition and topology views"},{title:"Evidence timeline"},{title:"Owner, work, and acknowledgement state"},{title:"Approval and workflow state"},{title:"Telemetry freshness and quality"},{title:"Verified outcome contract"}]}
    useCases={["Data Center Cooling command view","Operations and maintenance response board","Shift handoff with unresolved Conditions","Asset and affected-topology review","Evidence and source-health review","Verified recovery and recurrence monitoring"]}
    relatedProducts={[{label:"Infinit-Signal",to:"/infinit-signal",copy:"Qualifies evidence and creates the Condition."},{label:"Singularity",to:"/singularity",copy:"Provides shared operational context."},{label:"Infinit-Flow",to:"/infinit-flow",copy:"Coordinates work and action."},{label:"Last Mile Platform",to:"/platform"}]}
    faqs={[{question:"Is Infinit-Control a generic dashboard?",answer:"No. It is a role-based operational command surface centered on accountable Conditions, active response, current evidence, and verified physical outcomes."},{question:"Does it replace HMI, SCADA, or historian interfaces?",answer:"No. Those systems retain their control and source roles. Infinit-Control presents cross-system accountability above them."},{question:"Does it create another truth store?",answer:"No. It draws from the shared operational identity and memory in Singularity."}]}
    resources={[{label:"Platform overview",to:"/platform"},{label:"Data Center Cooling reference use case",to:"/data-center-cooling"},{label:"Signal 2 Action",to:"/signal-to-action"}]} />
  </>;
}
