import { SEO } from "@/app/components/SEO";
import { ProductPageLayout } from "@/app/components/ProductPageLayout";
import { createBreadcrumbSchema, createProductSchema } from "@/app/lib/structuredData";

export function SSOMPage() {
  const description="Singularity is the SSOM-based operational memory and OT world model that gives assets, Conditions, actions, evidence, time, and outcomes one shared identity.";
  return <><SEO title="Singularity | Understand and Remember Physical Operations" description={description} canonicalPath="/singularity" jsonLd={[createProductSchema("Singularity","/singularity",description),createBreadcrumbSchema([{name:"Home",path:"/"},{name:"Singularity",path:"/singularity"}])]} />
  <ProductPageLayout eyebrow="Understand + Remember" title="Give every asset, Condition, action, and outcome one shared operational identity." intro="Singularity is the SSOM-based operational memory and OT world model inside the Last Mile Platform. It connects assets, topology, Conditions, work, decisions, evidence, time, and outcomes without creating a competing source-system truth." primaryCta={{label:"Discuss Your Operational Model",to:"/contact?intent=architecture"}} secondaryCta={{label:"Explore the Platform",to:"/platform"}}
    overview={{heading:"One semantic contract across the response.",copy:["SSOM is the semantic contract inside Singularity. It defines how Last Mile represents operational identity, relationships, evidence, time, Conditions, actions, and outcomes.","Singularity works above existing historians and systems of record. It preserves the cross-system context and operational history needed to understand what happened, what it affected, what was done, and what the physical result proved."],children:<div className="lm-split-note"><article><h3>Customer operational memory</h3><p>Customer identity, topology, Conditions, evidence, actions, and outcomes remain tenant-isolated as part of normal operations.</p></article><article><h3>Future Data Trust contribution</h3><p>Any contribution would be optional, policy-approved, anonymized where required, and separate from normal customer operations.</p></article></div>}}
    benefits={[{title:"Shared identity across systems"},{title:"Time-correct operational context"},{title:"Evidence-backed AI context"},{title:"Response and recurrence history"},{title:"Topology-aware impact understanding"},{title:"Learning without replacing source truth"}]}
    features={[{title:"SSOM semantic contract"},{title:"Asset and dependency topology"},{title:"Condition lifecycle and evidence"},{title:"Decision, work, and approval context"},{title:"Source and semantic lineage"},{title:"Verified outcome history"}]}
    useCases={["Resolve one asset across conflicting source identities","Understand affected topology during a thermal excursion","Reconstruct a Condition, decision, work, and outcome timeline","Compare recurrence and response patterns where policy permits","Give governed AI time-correct operational context"]}
    relatedProducts={[{label:"Infinit-Signal",to:"/infinit-signal",copy:"Creates trusted operational records."},{label:"Infinit-Flow",to:"/infinit-flow",copy:"Uses context to coordinate action."},{label:"Infinit-Control",to:"/infinit-control",copy:"Presents the live operating state."},{label:"Last Mile Platform",to:"/platform"}]}
    faqs={[{question:"Is Singularity a historian replacement?",answer:"No. It connects source-system evidence with identity, topology, decisions, work, and outcomes while source systems retain their established roles."},{question:"What is SSOM?",answer:"SSOM is the semantic contract inside Singularity for operational identity, relationships, evidence, time, Conditions, actions, and outcomes."},{question:"Is customer memory shared?",answer:"No. Customer operational memory remains tenant-isolated. Any future Data Trust contribution would be optional and separately governed."}]}
    resources={[{label:"Platform architecture",to:"/platform"},{label:"Data Center Cooling reference use case",to:"/data-center-cooling"},{label:"Signal 2 Action",to:"/signal-to-action"}]} />
  </>;
}
