---
deployment:
  tasks:
    - export DEPLOYPATH=/home/hh0h355mndjv/public_html/
    - export NODEJS_VERSION=20
    - source /opt/nvm/nvm.sh
    - nvm use $NODEJS_VERSION
    - npm install
    - npm run build
    - shopt -s dotglob
    - /bin/cp -r dist/* $DEPLOYPATH
