---
deployment:
  tasks:
    - export DEPLOYPATH=/home/hh0h355mndjv/public_html/
    - /bin/cp dist/index.html $DEPLOYPATH
    - /bin/cp dist/favicon.svg $DEPLOYPATH
    - /bin/cp -r dist/assets $DEPLOYPATH
